In [ ]:
import numpy as np

temperatures_w1 =np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)
print(type(temperatures_w1))
print(temperatures_w1.shape) #shape
print(temperatures_w1.size) # Number of elements
print(temperatures_w1.dtype) # data type
print(temperatures_w1.ndim) # dimension


[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
<class 'numpy.ndarray'>
(7,)
7
float64
1


In [ ]:
# conversion
temperatures_w1_farhenheit = (temperatures_w1* 9/5) + 32
print(temperatures_w1_farhenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [ ]:
first_three_days = temperatures_w1[0:3]
print(first_three_days)

[22.5 25.3 20.8]


In [ ]:
weekend = temperatures_w1[-2:]
print(weekend)
Middle = temperatures_w1[2:5]
print(Middle)


[24.8 21.9]
[20.8 23.4 26.1]


In [ ]:
 #Row_1: [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] #(Week 1)
 #Row_2: [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1] #(Week 2)

 temperature = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
print(temperature.shape) #shape
print( temperature.size) # no. of elements
print( temperature.dtype) # type


(2, 7)
14
float64


In [1]:
#pandas series
import pandas as pd
marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'],
    name='marks')
print(marks)


Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: marks, dtype: int64


In [10]:
print(marks.iloc[0]) # first
print(marks.iloc[0:3]) #first 3
print(marks.iloc[2]) #3 rank




95
Rank1    95
Rank2    92
Rank3    89
Name: marks, dtype: int64
89


In [32]:
import pandas as pd
transactions =pd.DataFrame({'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
'ProductCategory': [ 'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],
    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})


print("Transactions DataFrame:")
print(transactions)

Transactions DataFrame:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [39]:
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.info)



   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
(10, 4)
Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')
<bound method DataFrame.info of    TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106

In [33]:
print(transactions[['ProductCategory', 'Amount']]) # product category and amount

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400


In [16]:
print(transactions.iloc[:, -3:]) #last 3

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400


In [17]:
    print(transactions[(transactions['Region'] == 'North') & (transactions['Amount'] > 200)]) #greater than 200

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400


In [27]:
print(transactions['ProductCategory'].value_counts()) #value count for product category

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64


In [28]:
print(transactions['Region'].unique()) #unique region


['North' 'South' 'East' 'West']


In [31]:
print(transactions.groupby('Region')['Amount'].mean()) #groupby


Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64


In [43]:
transactions.loc[
    transactions['TransactionID'] == 102, 'Amount'
] = 165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [55]:
transactions['Discount'] = transactions['Amount'] * 0.10
print(transactions)
print("transactions DataFrame")

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0
transactions DataFrame


In [58]:
transactions.drop(8,inplace=True)


KeyError: '[8] not found in axis'

In [66]:
transactions = transactions.drop(columns=['Discount'])


KeyError: "['Discount'] not found in axis"

In [64]:
print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400


In [ ]:
transactions = transactions.drop(columns=['Discount'])
